

typos = {
    r'sacrafice'    : r'sacrifice',
    r'discours'     : r'discourse',
    r'travling'      : r'traveling',
    r'oclock'       : r'oclock',
    r'[Ww]\. [Ww]oodruff' : r'Wilford Woodruff',
    r'any whare'    : r'anywhere',
    r'somewhare'     : r'somewhere',
    r'whare'         : r'where',
    r'sumthing'      : r'something',
    r' els '         : r' else ',
    r'savio saviour' : r'saviour',
    r'intirely    ' : r'entirely',
    r'phylosophers' : r'philosophers',
    r'baptised'     : r'baptized',
    r'benef\- it'   : r'benefit',
    r'preachi \-ng'      : r'preaching',
    r'oppor- tunities' : r'opportunities',
    r'vary'         : r'very',
    r'Councellor'   : r'Counselor',
    r'councellor'   : r'counselor',
    r'sircumstances' : r'circumstances',
    r'Preasent'    : r'present',
    r'Sept\.'      : r'September',
    r'Sacramento Sacramento' : r'Sacramento',
    r'tryed'       : r'tried',
    r'fals'        : r'false',
    r'Aprail'      : r'April',
    r'untill'      : r'until',
    }

symbols = {
        # 'b\. 1795':'',
        r'(, b\.)'              : r'',
        r'\<U\+25CA\>'          : r'',
        r'\&amp;c?'             : r"and",
        r'\&apos;'              : r"'",
        r"(\^?FIGURES?\^?)"     : r'',
        r'[\{\}\~]'             : r'',
        r'\s{2}'                : r' ',
        r','                    : r'',
        r'\[(\w+)\]'            : r'',
        r'\n'                   : r' ',
        r'\[\[(.*?)\|(.*?)\]\]' : r'\1',
        r'\- '                  : r'',
        r' ng '                 : r'ng ',
        r' ed '                 : r'ed ',
        r'\n'                 : r' ',
        r'\s+'                 : r' ',
        r'\.'                 : r'',
    }

entries_to_remove = [
    'WW 1841-2',
    'Front cover',
    'THE SECOND BOOK OF WILLFORD FOR 1839',
    'W\. WOODRUFFs DAILY JOURNAL AND HISTORY IN 1842',
    "WILFORD WOODRUFF's DAILY JOURNAL AND HISTORY IN 1843",
    "WILLFORD WOODRUFF'S JOURNAL VOL\. 2\. AND A SYNOPSIS OF VOL\. 1\.",
    "Willford Woodruff's Journal Containing an Account Of my life and travels from the time of my first connextion with the Church of Jesus Christ of Latter-day Saints",
    'THE FIRST BOOK OF WILLFORD VOL\. 2\. FOR 1838',
    r"WILLFORD\. WOORUFF's DAILY JOURNAL AND TRAVELS",
    r'Pgs\. 172\–288 are blank',
    ]

