project:
  type: website


website:
  url: 'https://porter.quarto.pub/woodruff_papers-c103'

  title: "Woodruff Papers Scripture Matches"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        file: woodruff_papers.qmd
  sidebar:
    contents: auto
# source: woodruff_papers.qmd
  # quarto-pub:
    # - id: bc8b2401-1fe0-46df-aafc-dc0705595d27

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
